In [1]:
import pandas as pd
import numpy as np

In [8]:
df_food_data=pd.read_csv(r"C:\Users\dtrri\bot\food_data.csv")

In [9]:
df=df_food_data.copy()

In [10]:
df

GPA  Gender  breakfast  calories_day  coffee  \
0      2.4       2          1           NaN       1   
1    3.654       1          1           3.0       2   
2      3.3       1          1           4.0       2   
3      3.2       1          1           3.0       2   
4      3.5       1          1           2.0       2   
..     ...     ...        ...           ...     ...   
122      3       1          1           2.0       2   
123  3.882       1          1           NaN       1   
124      3       2          1           4.0       1   
125    3.9       1          1           NaN       2   
126    3.9       1          1           NaN       2   

                         comfort_food  cuisine eating_changes_coded1  \
0                                none      NaN                     1   
1         chocolate, chips, ice cream      1.0                     2   
2     frozen yogurt, pizza, fast food      3.0                     3   
3    Pizza, Mac and cheese, ice cream      2.0                     3   
4        Ice cream, chocolate, chips       2.0                     4   
..                                ...      ...                   ...   
122        Pizza / Wings / Cheesecake      NaN                     3   
123        rice, potato, seaweed soup      NaN                     3   
124      Mac n Cheese, Lasagna, Pizza      1.0                     8   
125      Chocolates, pizza, and Ritz.      3.0                     5   
126      Chocolates, pizza, and Ritz.      3.0                     5   

     father_education             father_profession        fav_cuisine  \
0                 5.0                     profesor      Arabic cuisine   
1                 2.0                Self employed             Italian   
2                 2.0                 owns business            italian   
3                 2.0                     Mechanic            Turkish    
4                 4.0                            IT           Italian    
..                ...                           ...                ...   
122               5.0                        Doctor       Mexican Food   
123               5.0                CEO of company             Korean   
124               3.0  Store manager at Giant Eagle            Italian   
125               4.0                    Journalist  HISPANIC CUISINE.   
126               4.0                    Journalist  HISPANIC CUISINE.   

    fav_cuisine_coded  fav_food  fries  fruit_day  marital_status  \
0                   3       1.0      2          5             1.0   
1                   1       1.0      1          4             2.0   
2                   1       3.0      1          5             2.0   
3                   3       1.0      2          4             2.0   
4                   1       3.0      1          4             1.0   
..                ...       ...    ...        ...             ...   
122                 2       1.0      1          4             1.0   
123                 4       1.0      1          4             1.0   
124                 1       3.0      1          5             1.0   
125                 2       1.0      1          3             2.0   
126                 2       1.0      1          3             2.0   

     mother_education                          mother_profession  
0                 1.0                                 unemployed  
1                 4.0                                  Nurse RN   
2                 2.0                              owns business  
3                 4.0                  Special Education Teacher  
4                 5.0                   Substance Abuse Conselor  
..                ...                                        ...  
122               2.0                     Public Health Advisor   
123               1.0                       Real Estate manageer  
124               2.0  Receptionist for a medical supply company  
125               3.0                                 House-wife  
126               3.0     

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127 entries, 0 to 126
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   GPA                    125 non-null    object 
 1   Gender                 127 non-null    int64  
 2   breakfast              127 non-null    int64  
 3   calories_day           106 non-null    float64
 4   coffee                 127 non-null    int64  
 5   comfort_food           126 non-null    object 
 6   cuisine                110 non-null    float64
 7   eating_changes_coded1  127 non-null    object 
 8   father_education       126 non-null    float64
 9   father_profession      124 non-null    object 
 10  fav_cuisine            124 non-null    object 
 11  fav_cuisine_coded      127 non-null    object 
 12  fav_food               125 non-null    float64
 13  fries                  127 non-null    int64  
 14  fruit_day              127 non-null    int64  
 15  marita

## duplicate handeling

In [12]:
df.duplicated().sum()

4

In [15]:
df.drop_duplicates(inplace=True)

In [16]:
df

GPA  Gender  breakfast  calories_day  coffee  \
0      2.4       2          1           NaN       1   
1    3.654       1          1           3.0       2   
2      3.3       1          1           4.0       2   
3      3.2       1          1           3.0       2   
4      3.5       1          1           2.0       2   
..     ...     ...        ...           ...     ...   
121    3.5       1          1           4.0       2   
122      3       1          1           2.0       2   
123  3.882       1          1           NaN       1   
124      3       2          1           4.0       1   
125    3.9       1          1           NaN       2   

                                comfort_food  cuisine eating_changes_coded1  \
0                                       none      NaN                     1   
1                chocolate, chips, ice cream      1.0                     2   
2            frozen yogurt, pizza, fast food      3.0                     3   
3           Pizza, Mac and cheese, ice cream      2.0                     3   
4               Ice cream, chocolate, chips       2.0                     4   
..                                       ...      ...                   ...   
121  wine. mac and cheese, pizza, ice cream       1.0                     3   
122               Pizza / Wings / Cheesecake      NaN                     3   
123               rice, potato, seaweed soup      NaN                     3   
124             Mac n Cheese, Lasagna, Pizza      1.0                     8   
125             Chocolates, pizza, and Ritz.      3.0                     5   

     father_education             father_profession        fav_cuisine  \
0                 5.0                     profesor      Arabic cuisine   
1                 2.0                Self employed             Italian   
2                 2.0                 owns business            italian   
3                 2.0                     Mechanic            Turkish    
4                 4.0                            IT           Italian    
..                ...                           ...                ...   
121               4.0                   Accountant            Italian    
122               5.0                        Doctor       Mexican Food   
123               5.0                CEO of company             Korean   
124               3.0  Store manager at Giant Eagle            Italian   
125               4.0                    Journalist  HISPANIC CUISINE.   

    fav_cuisine_coded  fav_food  fries  fruit_day  marital_status  \
0                   3       1.0      2          5             1.0   
1                   1       1.0      1          4             2.0   
2                   1       3.0      1          5             2.0   
3                   3       1.0      2          4             2.0   
4                   1       3.0      1          4             1.0   
..                ...       ...    ...        ...             ...   
121                 1       1.0      1          5             1.0   
122                 2       1.0      1          4             1.0   
123                 4       1.0      1          4             1.0   
124                 1       3.0      1          5             1.0   
125                 2       1.0      1          3             2.0   

     mother_education                          mother_profession  
0                 1.0                                 unemployed  
1                 4.0                                  Nurse RN   
2                 2.0                              owns business  
3                 4.0                  Special Education Teacher  
4                 5.0                   Substance Abuse Conselor  
..                ...                                        ...  
121               3.0                   Radiological Technician   
122               2.0                     Public Health Advisor   
123               1.0                       Real Estate manageer  
124      

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 123 entries, 0 to 125
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   GPA                    121 non-null    object 
 1   Gender                 123 non-null    int64  
 2   breakfast              123 non-null    int64  
 3   calories_day           104 non-null    float64
 4   coffee                 123 non-null    int64  
 5   comfort_food           122 non-null    object 
 6   cuisine                106 non-null    float64
 7   eating_changes_coded1  123 non-null    object 
 8   father_education       122 non-null    float64
 9   father_profession      120 non-null    object 
 10  fav_cuisine            120 non-null    object 
 11  fav_cuisine_coded      123 non-null    object 
 12  fav_food               121 non-null    float64
 13  fries                  123 non-null    int64  
 14  fruit_day              123 non-null    int64  
 15  marital_sta

In [25]:
import re
def remove_invalid_symbols(string):
    return re.sub(r'[^\W\S]', np.nan, string)

In [22]:
df.describe()

Gender   breakfast  calories_day         coffee     cuisine  \
count  1.230000e+02  123.000000    104.000000     123.000000  106.000000   
mean   8.362049e+03    1.113821      3.038462    4114.195122    1.396226   
std    9.018223e+04    0.318893      0.637396   30887.281453    0.982506   
min    1.000000e+00    1.000000      2.000000       1.000000    1.000000   
25%    1.000000e+00    1.000000      3.000000       2.000000    1.000000   
50%    1.000000e+00    1.000000      3.000000       2.000000    1.000000   
75%    2.000000e+00    1.000000      3.000000       2.000000    1.000000   
max    1.000001e+06    2.000000      4.000000  283731.000000    6.000000   

       father_education    fav_food       fries   fruit_day  marital_status  \
count        122.000000  121.000000  123.000000  123.000000      122.000000   
mean           3.483607    1.710744    1.089431    4.211382        1.491803   
std            1.200782    0.907726    0.286532    0.925522        0.549168   
min            1.000000    1.000000    1.000000    1.000000        1.000000   
25%            2.000000    1.000000    1.000000    4.000000        1.000000   
50%            4.000000    1.000000    1.000000    4.000000        1.000000   
75%            4.000000    3.000000    1.000000    5.000000        2.000000   
max            5.000000    3.000000    2.000000    5.000000        4.000000   

       mother_education  
count        120.000000  
mean           3.433333  
std            1.179185  
min            1.000000  
25%            2.000000  
50%            4.000000  
75%            4.000000  
max            5.000000

In [23]:
df.columns

Index(['GPA', 'Gender', 'breakfast', 'calories_day', 'coffee', 'comfort_food',
       'cuisine', 'eating_changes_coded1', 'father_education',
       'father_profession', 'fav_cuisine', 'fav_cuisine_coded', 'fav_food',
       'fries', 'fruit_day', 'marital_status', 'mother_education',
       'mother_profession'],
      dtype='object')

## gpa invalid values and null handeling ->mean

In [24]:
df['GPA'].unique()

array(['2.4', '3.654', '3.3', '3.2', '3.5', '2.25', '3.8', '3.904', '3.4',
       '3.6', '3.1', nan, '4', '2.2', '3.87', '3.7', '3.9', '2.8', '3',
       '3.65', '3.89', '2.9', '3.605', '3.83', '3.292', '3.35',
       'Personal ', '2.6', '3.67', '3.73', '2.71', '3.68', '3.75', '3.92',
       'Unknown', '3.77', '3.63', '3.882'], dtype=object)

In [31]:
df['GPA'].replace(['Personal ','Unknown'],np.nan,inplace=True)

In [32]:
df['GPA'].unique()

array(['2.4', '3.654', '3.3', '3.2', '3.5', '2.25', '3.8', '3.904', '3.4',
       '3.6', '3.1', nan, '4', '2.2', '3.87', '3.7', '3.9', '2.8', '3',
       '3.65', '3.89', '2.9', '3.605', '3.83', '3.292', '3.35', '2.6',
       '3.67', '3.73', '2.71', '3.68', '3.75', '3.92', '3.77', '3.63',
       '3.882'], dtype=object)

In [110]:
df['GPA']=df['GPA'].astype(float)

In [111]:
df['GPA']=df['GPA'].fillna(df['GPA'].mean())

In [112]:
df['GPA'].isnull().sum()

0

## gender invalid values -> mode

In [33]:
df['Gender'].unique()

array([      2,       1,   28362, 1000001], dtype=int64)

In [37]:
df['Gender']=df['Gender'].replace([28362,1000001],np.nan)

In [38]:
df['Gender'].unique()

array([ 2.,  1., nan])

In [107]:
df['Gender']=df['Gender'].fillna(df['Gender'].mode()[0])

In [108]:
df['Gender'].unique()

array([2., 1.])

## checking breakfast invalid values

In [39]:
df['breakfast'].unique()

array([1, 2], dtype=int64)

## checking 'calories_day' invalid values and null handeling -> mean

In [40]:
df['calories_day'].unique()

array([nan,  3.,  4.,  2.])

In [105]:
df['calories_day']=df['calories_day'].fillna(df['calories_day'].mean())

In [106]:
df['calories_day'].unique()

array([3.03846154, 3.        , 4.        , 2.        ])

## checking 'coffee' invalid values and null handeling -> mode

In [41]:
df['coffee'].unique()

array([     1,      2,  10001,  18372, 283731, 193732], dtype=int64)

In [42]:
df['coffee']=df['coffee'].replace([10001,18372,283731,193732],np.nan)

In [43]:
df['coffee'].unique()

array([ 1.,  2., nan])

In [103]:
df['coffee']=df['coffee'].fillna(df['coffee'].mode()[0])

In [104]:
df['coffee'].isnull().sum()

0

## 'comfort_food' invalid values and null handeling ->mode

In [44]:
df['comfort_food'].unique()

array(['none', 'chocolate, chips, ice cream',
       'frozen yogurt, pizza, fast food',
       'Pizza, Mac and cheese, ice cream', 'Ice cream, chocolate, chips ',
       'Candy, brownies and soda.',
       'Chocolate, ice cream, french fries, pretzels',
       'Ice cream, cheeseburgers, chips.', 'Donuts, ice cream, chips',
       'Mac and cheese, chocolate, and pasta ',
       'Pasta, grandma homemade chocolate cake anything homemade ',
       'chocolate, pasta, soup, chips, popcorn',
       'Cookies, popcorn, and chips', 'ice cream, cake, chocolate',
       'Pizza, fruit, spaghetti, chicken and Potatoes  ',
       'cookies, donuts, candy bars', 'Saltfish, Candy and Kit Kat ',
       'chips, cookies, ice cream', 'Chocolate, ice crea ',
       'pizza, wings, Chinese', 'Fast food, pizza, subs',
       'chocolate, sweets, ice cream', 'burgers, chips, cookies',
       'Chilli, soup, pot pie', 'Soup, pasta, brownies, cake',
       'chocolate, ice cream/milkshake, cookies',
       'Chips, ic

In [100]:
df['comfort_food'].isnull().sum()

1

In [101]:
df['comfort_food']=df['comfort_food'].fillna(df['comfort_food'].mode()[0])

In [102]:
df['comfort_food'].isnull().sum()

0

## 'cuisine' invalid values and null handeling

In [99]:
df['cuisine'].unique()

array([nan,  1.,  3.,  2.,  6.,  4.,  5.])

In [115]:
df['cuisine'].isnull().sum()

17

In [116]:
df['cuisine']=df['cuisine'].fillna(df['cuisine'].mode()[0])

In [117]:
df['cuisine'].isnull().sum()

0

## 'eating_changes_coded1' invalid values and null handeling

In [46]:
df['eating_changes_coded1'].unique()

array(['1', '2', '3', '4', '5', '8', 'Four', '6', '7', '9', '10', '11',
       '12', '13'], dtype=object)

In [96]:
df['eating_changes_coded1']=df['eating_changes_coded1'].replace(['Four'],4)

In [97]:
df['eating_changes_coded1']=df['eating_changes_coded1'].astype(int)

In [98]:
df['eating_changes_coded1'].unique()

array([ 1,  2,  3,  4,  5,  8,  6,  7,  9, 10, 11, 12, 13])

## father_education invalid values and null handeling ->mode

In [47]:
df['father_education'].unique()

array([ 5.,  2.,  4.,  1.,  3., nan])

In [94]:
df['father_education']=df['father_education'].fillna(df['father_education'].mode()[0])

In [95]:
df['father_education'].isnull().sum()

0

## father_profession invalid  values and null handeling ->mode

In [48]:
df['father_profession'].unique()

array(['profesor ', 'Self employed ', 'owns business', 'Mechanic ', 'IT',
       'T', 'Assembler ', 'Business guy', 'High School Principal',
       'commissioner of erie county ', 'Idk', 'Home Marker ',
       'Shirt designer ', 'business owner', 'Commidity trader ',
       'Hockey Coach', 'C', 'self employed construction ', 'Engineer',
       'architect', 'CFO', 'European logistics director ', 'accountant ',
       'Commercial Real Estate', 'Manager at Pepsi', 'VP of ',
       'Beverage and Food Sales', 'Dentist ', 'Electrical Engineer',
       'Radio Telecommunications Manager', nan, 'deceased', 'Lawyer',
       'landscaping ', 'Vice President of a company',
       'Owns his own promotional company ', 'Optometrist ',
       'Construction ', 'Biohemical Waste Elimination',
       'Corporate Manager ', 'Small business owner ', 'Welder',
       'Design Engineer', 'Unknown ', 'Banker', 'subcontractor ',
       'small business owner ', 'House Appraiser', 'not sure', 'Fireman',
       'Pre

In [51]:
df['father_profession']=df['father_profession'].replace(['T','Idk','C','VP of ','Unknown ','not sure','Dead beat ','T$'],np.nan)

In [91]:
df['father_profession'].isnull().sum()

11

In [92]:
df['father_profession']=df['father_profession'].fillna(df['father_profession'].mode()[0])

In [93]:
df['father_profession'].isnull().sum()

0

## 'fav_cuisine' invalid values null handeling -> mode

In [55]:
df['fav_cuisine'].unique()

array(['Arabic cuisine', 'Italian', 'italian', 'Turkish ', 'Italian ',
       'African', 'Thai', 'Anything american style.', 'Seafood',
       'Orange chicken and chow mani noodles ', 'Chinese ',
       'italian food', 'Jamaican ', 'American or Italian ', 'Chicken ',
       'Mexican', 'Indian', 'italian ', nan, 'Chinese', "don't have one",
       'Italian food ', 'Mexican ', 'Italian/German',
       'Indian food - samosas are amazing', 'mexican', 'Spanish',
       'French', 'American or Italian', 'Italian or Chinese ', 'chinese',
       'Thai food', 'Greek', 'Asian ', 'American', 'All ',
       'Sub sandwhiches', 'Wraps ', "Chinese cuisine (General Tso's)",
       'American ', 'Lean', 'american ', 'Japanese',
       'Any type of Colombian cuisine', 'Mexican cuisine', 'Chinese food',
       'mac and cheese', 'Authentic Chinese and Vietnamese food ',
       'italian and chinese', 'Barbecue ', 'lebanese or greek', 'sushi',
       'Indian food', 'Nepali',
       'I really love italian food

In [56]:
df['fav_cuisine']=df['fav_cuisine'].replace(['I'],np.nan)

In [88]:
df['fav_cuisine'].isnull().sum()

4

In [89]:
df['fav_cuisine']=df['fav_cuisine'].fillna(df['fav_cuisine'].mode()[0])

In [90]:
df['fav_cuisine'].isnull().sum()

0

## fav_cuisine_coded invalid values null handeling

In [57]:
df['fav_cuisine_coded'].unique()

array(['3', '1', '6', '4', '5', 'Seven', '2', '8', '0', 'One'],
      dtype=object)

In [58]:
df['fav_cuisine_coded']=df['fav_cuisine_coded'].replace('Seven',7)

In [59]:
df['fav_cuisine_coded']=df['fav_cuisine_coded'].replace('One',1)

In [63]:
df['fav_cuisine_coded']=df['fav_cuisine_coded'].astype(int)

In [64]:
df['fav_cuisine_coded'].unique()

array([3, 1, 6, 4, 5, 7, 2, 8, 0])

## 'fav_food' invalid values and null handeling ->mode

In [65]:
df['fav_food'].unique()

array([ 1.,  3.,  2., nan])

In [86]:
df['fav_food']=df['fav_food'].fillna(df['fav_food'].mode()[0])

In [87]:
df['fav_food'].unique()

array([1., 3., 2.])

In [66]:
df.columns

Index(['GPA', 'Gender', 'breakfast', 'calories_day', 'coffee', 'comfort_food',
       'cuisine', 'eating_changes_coded1', 'father_education',
       'father_profession', 'fav_cuisine', 'fav_cuisine_coded', 'fav_food',
       'fries', 'fruit_day', 'marital_status', 'mother_education',
       'mother_profession'],
      dtype='object')

## 'fries' invalid values and null handeling

In [67]:
df['fries'].unique()

array([2, 1], dtype=int64)

## fruit_day invalid values and null handeling

In [68]:
df['fruit_day'].unique()

array([5, 4, 2, 3, 1], dtype=int64)

## marital_status invalid values and null handeling -> mode

In [69]:
df['marital_status'].unique()

array([ 1.,  2.,  4., nan])

In [82]:
df['marital_status']=df['marital_status'].fillna(df['marital_status'].mode()[0])

In [83]:
df['marital_status'].unique()

array([1., 2., 4.])

## mother_education invalid  and null handeling -> mode

In [70]:
df['mother_education'].unique()

array([ 1.,  4.,  2.,  5.,  3., nan])

In [80]:
df['mother_education']=df['mother_education'].fillna(df['mother_education'].mode()[0])

In [81]:
df['mother_education'].unique()

array([1., 4., 2., 5., 3.])

## mother_profession invalid values and null handeling -> mode

In [71]:
df['mother_profession'].unique()

array(['unemployed', 'Nurse RN ', 'owns business',
       'Special Education Teacher', 'Substance Abuse Conselor',
       'Hair Braider', 'Journalist', 'cook', 'Elementary School Teacher',
       'Pharmaceutical rep', 'Chidos Cleaners', '10',
       'Child care provider ', 'business owner', 'Charity worker',
       'Librarian', 'Police', 'stay at home mom', 'Daycare provider',
       'physical therapist', 'Teacher', 'House wife', 'Underwiriter ',
       'Beautician ', 'Unemployed', 'Medical biller',
       'Doctors Billing Assiant ', 'Dentist ', 'Air Traffic Controller',
       'Strategic Planning and Programs Manager', 'teacher', 'management',
       'Lawyer', 'stylist', 'Works in retail', 'Homemaker ',
       'Head of Human Resouces', 'Accountant', 'Marketing Analyst',
       'Middle school teacher', 'Art teacher ', 'Account Clerical ',
       'Caretaker', 'Secretary', 'Registered Nurse', 'telemarketer ',
       'nurse', 'Banker', 'Office assistant', 'Stay home', 'Unemployed ',
     

In [72]:
df['mother_profession']=df['mother_profession'].replace(['10'],np.nan)

In [78]:
df['mother_profession']=df['mother_profession'].fillna(df['mother_profession'].mode()[0])

In [79]:
df['mother_profession'].unique()

array(['unemployed', 'Nurse RN ', 'owns business',
       'Special Education Teacher', 'Substance Abuse Conselor',
       'Hair Braider', 'Journalist', 'cook', 'Elementary School Teacher',
       'Pharmaceutical rep', 'Chidos Cleaners', 'Secretary',
       'Child care provider ', 'business owner', 'Charity worker',
       'Librarian', 'Police', 'stay at home mom', 'Daycare provider',
       'physical therapist', 'Teacher', 'House wife', 'Underwiriter ',
       'Beautician ', 'Unemployed', 'Medical biller',
       'Doctors Billing Assiant ', 'Dentist ', 'Air Traffic Controller',
       'Strategic Planning and Programs Manager', 'teacher', 'management',
       'Lawyer', 'stylist', 'Works in retail', 'Homemaker ',
       'Head of Human Resouces', 'Accountant', 'Marketing Analyst',
       'Middle school teacher', 'Art teacher ', 'Account Clerical ',
       'Caretaker', 'Registered Nurse', 'telemarketer ', 'nurse',
       'Banker', 'Office assistant', 'Stay home', 'Unemployed ',
       'Cou

# cleaned data

In [118]:
df

GPA  Gender  breakfast  calories_day  coffee  \
0    2.400     2.0          1      3.038462     1.0   
1    3.654     1.0          1      3.000000     2.0   
2    3.300     1.0          1      4.000000     2.0   
3    3.200     1.0          1      3.000000     2.0   
4    3.500     1.0          1      2.000000     2.0   
..     ...     ...        ...           ...     ...   
121  3.500     1.0          1      4.000000     2.0   
122  3.000     1.0          1      2.000000     2.0   
123  3.882     1.0          1      3.038462     1.0   
124  3.000     2.0          1      4.000000     1.0   
125  3.900     1.0          1      3.038462     2.0   

                                comfort_food  cuisine  eating_changes_coded1  \
0                                       none      1.0                      1   
1                chocolate, chips, ice cream      1.0                      2   
2            frozen yogurt, pizza, fast food      3.0                      3   
3           Pizza, Mac and cheese, ice cream      2.0                      3   
4               Ice cream, chocolate, chips       2.0                      4   
..                                       ...      ...                    ...   
121  wine. mac and cheese, pizza, ice cream       1.0                      3   
122               Pizza / Wings / Cheesecake      1.0                      3   
123               rice, potato, seaweed soup      1.0                      3   
124             Mac n Cheese, Lasagna, Pizza      1.0                      8   
125             Chocolates, pizza, and Ritz.      3.0                      5   

     father_education             father_profession        fav_cuisine  \
0                 5.0                     profesor      Arabic cuisine   
1                 2.0                Self employed             Italian   
2                 2.0                 owns business            italian   
3                 2.0                     Mechanic            Turkish    
4                 4.0                            IT           Italian    
..                ...                           ...                ...   
121               4.0                   Accountant            Italian    
122               5.0                        Doctor       Mexican Food   
123               5.0                CEO of company             Korean   
124               3.0  Store manager at Giant Eagle            Italian   
125               4.0                    Journalist  HISPANIC CUISINE.   

     fav_cuisine_coded  fav_food  fries  fruit_day  marital_status  \
0                    3       1.0      2          5             1.0   
1                    1       1.0      1          4             2.0   
2                    1       3.0      1          5             2.0   
3                    3       1.0      2          4             2.0   
4                    1       3.0      1          4             1.0   
..                 ...       ...    ...        ...             ...   
121                  1       1.0      1          5             1.0   
122                  2       1.0      1          4             1.0   
123                  4       1.0      1          4             1.0   
124                  1       3.0      1          5             1.0   
125                  2       1.0      1          3             2.0   

     mother_education                          mother_profession  
0                 1.0                                 unemployed  
1                 4.0                                  Nurse RN   
2                 2.0                              owns business  
3                 4.0                  Special Education Teacher  
4                 5.0                   Substance Abuse Conselor  
..                ...                                        ...  
121               3.0                   Radiological Technician   
122               2.0                     Public Health Advisor   
123               1.0                       Real Est

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 123 entries, 0 to 125
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   GPA                    123 non-null    float64
 1   Gender                 123 non-null    float64
 2   breakfast              123 non-null    int64  
 3   calories_day           123 non-null    float64
 4   coffee                 123 non-null    float64
 5   comfort_food           123 non-null    object 
 6   cuisine                123 non-null    float64
 7   eating_changes_coded1  123 non-null    int32  
 8   father_education       123 non-null    float64
 9   father_profession      123 non-null    object 
 10  fav_cuisine            123 non-null    object 
 11  fav_cuisine_coded      123 non-null    int32  
 12  fav_food               123 non-null    float64
 13  fries                  123 non-null    int64  
 14  fruit_day              123 non-null    int64  
 15  marital_sta