Q1.
a. Generate five NumPy arrays of different dimensions using arange().
b. Determine the datatype, shape, size, and dimensions of those arrays.

In [1]:
import numpy as np

In [19]:
a=np.arange(12).reshape(2,6)
print(a)
print(f'type : {type(a)}')
print(f'dimensions : {a.ndim}')
print(f'shape :{a.shape}')
print(f'type of elements : {a.dtype}')
print(f'size : {a.size}')

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
type : <class 'numpy.ndarray'>
dimensions : 2
shape :(2, 6)
type of elements : int32
size : 12


In [20]:
a=np.arange(12).reshape(3,4)
print(a)
print(f'type : {type(a)}')
print(f'dimensions : {a.ndim}')
print(f'shape :{a.shape}')
print(f'type of elements : {a.dtype}')
print(f'size : {a.size}')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
type : <class 'numpy.ndarray'>
dimensions : 2
shape :(3, 4)
type of elements : int32
size : 12


In [21]:
a=np.arange(12).reshape(6,2)
print(a)
print(f'type : {type(a)}')
print(f'dimensions : {a.ndim}')
print(f'shape :{a.shape}')
print(f'type of elements : {a.dtype}')
print(f'size : {a.size}')

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
type : <class 'numpy.ndarray'>
dimensions : 2
shape :(6, 2)
type of elements : int32
size : 12


In [22]:
a=np.arange(0,12).reshape(4,3)
print(a)
print(f'type : {type(a)}')
print(f'dimensions : {a.ndim}')
print(f'shape :{a.shape}')
print(f'type of elements : {a.dtype}')
print(f'size : {a.size}')

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
type : <class 'numpy.ndarray'>
dimensions : 2
shape :(4, 3)
type of elements : int32
size : 12


In [23]:
a=np.arange(12).reshape(12,1)
print(a)
print(f'type : {type(a)}')
print(f'dimensions : {a.ndim}')
print(f'shape :{a.shape}')
print(f'type of elements : {a.dtype}')
print(f'size : {a.size}')

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
type : <class 'numpy.ndarray'>
dimensions : 2
shape :(12, 1)
type of elements : int32
size : 12


Q2.
a. Generate five NumPy arrays of different dimensions using np.array().
b. Determine the datatype, shape, size, and dimensions of those arrays.

In [24]:
a=np.array([1,2,3])
print(a)
print(f'type : {type(a)}')
print(f'dimensions : {a.ndim}')
print(f'shape :{a.shape}')
print(f'type of elements : {a.dtype}')
print(f'size : {a.size}')

[1 2 3]
type : <class 'numpy.ndarray'>
dimensions : 1
shape :(3,)
type of elements : int32
size : 3


In [25]:
a=np.array([[1,2,3]])
print(a)
print(f'type : {type(a)}')
print(f'dimensions : {a.ndim}')
print(f'shape :{a.shape}')
print(f'type of elements : {a.dtype}')
print(f'size : {a.size}')

[[1 2 3]]
type : <class 'numpy.ndarray'>
dimensions : 2
shape :(1, 3)
type of elements : int32
size : 3


In [26]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(f'type : {type(a)}')
print(f'dimensions : {a.ndim}')
print(f'shape :{a.shape}')
print(f'type of elements : {a.dtype}')
print(f'size : {a.size}')

[[1 2 3]
 [4 5 6]]
type : <class 'numpy.ndarray'>
dimensions : 2
shape :(2, 3)
type of elements : int32
size : 6


In [27]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(f'type : {type(a)}')
print(f'dimensions : {a.ndim}')
print(f'shape :{a.shape}')
print(f'type of elements : {a.dtype}')
print(f'size : {a.size}')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
type : <class 'numpy.ndarray'>
dimensions : 2
shape :(3, 3)
type of elements : int32
size : 9


In [28]:
a=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a)
print(f'type : {type(a)}')
print(f'dimensions : {a.ndim}')
print(f'shape :{a.shape}')
print(f'type of elements : {a.dtype}')
print(f'size : {a.size}')

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
type : <class 'numpy.ndarray'>
dimensions : 3
shape :(3, 2, 3)
type of elements : int32
size : 18
