In [1]:
import cv2
import numpy as np

In [4]:
img=cv2.imread(r"D:\Downloads\4709944 vergil low res.jpg")

# sobel filter

In [23]:
img1=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img1=cv2.GaussianBlur(img1,(11,11),1)

In [25]:
ve=cv2.Sobel(img1,cv2.CV_32F,1,0,(10,10))
he=cv2.Sobel(img1,cv2.CV_32F,0,1,(10,10))
pe=cv2.Sobel(img1,cv2.CV_32F,1,1,(10,10))

In [27]:
cv2.imshow("ve",ve)
cv2.imshow("he",he)
cv2.imshow("pe",pe)
cv2.waitKey()
cv2.destroyAllWindows()

# laplacian filter

In [30]:
cv2.imshow("pe",cv2.Laplacian(img,cv2.CV_32F))
cv2.waitKey()
cv2.destroyAllWindows()

# canny filter

In [19]:
img1=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img1=cv2.GaussianBlur(img1,(5,5),1)
can=cv2.Canny(img1,10,90)
cv2.imshow("canny",can)
cv2.waitKey()
cv2.destroyAllWindows()

# canny filter with trackbar

In [21]:
img=cv2.imread(r"D:\coins image.jpg")
img1=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img1=cv2.GaussianBlur(img1,(7,7),1)
cv2.namedWindow("canny")
k=np.ones((3,3),dtype=np.uint8)
cv2.createTrackbar("low","canny",0,255,lambda x:None)
cv2.createTrackbar("high","canny",0,255,lambda x:None)
while True:
    l=cv2.getTrackbarPos("low","canny")
    h=cv2.getTrackbarPos("high","canny")
    img2=cv2.morphologyEx(img1,op=cv2.MORPH_CLOSE,kernel=k,iterations=5)
    can=cv2.Canny(img2,l,h)
    cv2.imshow("canny",can)
    if cv2.waitKey(1)==ord("c"):
        break
cv2.destroyAllWindows()

# countours

In [27]:
# first canny or thredholding then cauntours

In [83]:
# with canny edge

In [85]:
img=cv2.imread(r"D:\Downloads\4709944 vergil low res.jpg")

img1=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img1=cv2.GaussianBlur(img1,(7,7),1)
can=cv2.Canny(img1,22,61)

c,h=cv2.findContours(can,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)

draw_count=cv2.drawContours(img,c,-1,(0,255,0),2)

cv2.imshow("contour",draw_count)
cv2.waitKey()
cv2.destroyAllWindows()

In [125]:
# with threshold (too much stuff in this shit)

In [123]:
img=cv2.imread(r"D:\Downloads\4709944 vergil low res.jpg")

img1=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img1=cv2.GaussianBlur(img1,(7,7),1)
bin1=cv2.threshold(img1,100,255,cv2.THRESH_BINARY)[1]

c,h=cv2.findContours(bin1,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)

draw_count=cv2.drawContours(img,c,-1,(0,255,0),2)

cv2.imshow("threshold",bin1)
cv2.imshow("contour",draw_count)
cv2.waitKey()
cv2.destroyAllWindows()

# coins thing

In [6]:
img=cv2.imread(r"D:\coins image.jpg")

img1=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img1=cv2.GaussianBlur(img1,(7,7),1)
k=np.ones((5,5),dtype=np.uint8)
img2=cv2.morphologyEx(img1,op=cv2.MORPH_CLOSE,kernel=k,iterations=6)
can=cv2.Canny(img2,120,255)

c,h=cv2.findContours(can,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)

draw_count=cv2.drawContours(img,c,-1,(0,255,0),2)

cv2.imshow("contour",draw_count)
cv2.waitKey()
cv2.destroyAllWindows()

In [76]:
len(c)

22

In [7]:
h

array([[[ 1, -1, -1, -1],
        [ 2,  0, -1, -1],
        [ 3,  1, -1, -1],
        [ 4,  2, -1, -1],
        [ 5,  3, -1, -1],
        [ 6,  4, -1, -1],
        [ 7,  5, -1, -1],
        [ 8,  6, -1, -1],
        [ 9,  7, -1, -1],
        [10,  8, -1, -1],
        [11,  9, -1, -1],
        [12, 10, -1, -1],
        [13, 11, -1, -1],
        [14, 12, -1, -1],
        [15, 13, -1, -1],
        [16, 14, -1, -1],
        [17, 15, -1, -1],
        [18, 16, -1, -1],
        [19, 17, -1, -1],
        [20, 18, -1, -1],
        [21, 19, -1, -1],
        [-1, 20, -1, -1]]], dtype=int32)

# shapes thing

In [66]:
img=cv2.imread(r"D:\shapes_and_colors.jpg")

img1=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img1=cv2.GaussianBlur(img1,(7,7),1)
k=np.ones((5,5),dtype=np.uint8)
img2=cv2.morphologyEx(img1,op=cv2.MORPH_CLOSE,kernel=k,iterations=1)
can=cv2.Canny(img2,120,255)

c,h=cv2.findContours(can,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)

draw_count=cv2.drawContours(img,c,-1,(0,255,0),2)

cv2.imshow("contour",draw_count)
cv2.waitKey()
cv2.destroyAllWindows()

In [68]:
len(c)

17

# finding area using countours

In [25]:
img=cv2.imread(r"D:\Downloads\4709944 vergil low res.jpg")

img1=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img1=cv2.GaussianBlur(img1,(7,7),2)
can=cv2.Canny(img1,22,65)

c,h=cv2.findContours(can,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
sc=sorted(c,key=cv2.contourArea,reverse=True)
for i,c1 in enumerate(c):
    area=cv2.contourArea(c[i])
    cv2.drawContours(img,c,-1,(0,255,0),2)
    cv2.putText(img,str(area),(c1[0,0,0],c1[0,0,1]),cv2.FONT_HERSHEY_COMPLEX,0.5,(0,0,255),1)

cv2.imshow("contour",img)
cv2.waitKey()
cv2.destroyAllWindows()

In [27]:
img=cv2.imread(r"D:\Downloads\4709944 vergil low res.jpg")

img1=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img1=cv2.GaussianBlur(img1,(7,7),2)
can=cv2.Canny(img1,22,65)

c,h=cv2.findContours(can,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
sc=sorted(c,key=cv2.contourArea,reverse=True)
for i,c1 in enumerate(sc):
    cv2.drawContours(img,c1,-1,(0,255,0),2)
    cv2.putText(img,str(i),(c1[0,0,0],c1[0,0,1]),cv2.FONT_HERSHEY_COMPLEX,0.5,(0,0,255),1)

cv2.imshow("contour",img)
cv2.waitKey()
cv2.destroyAllWindows()

In [17]:
c[0][0,0,1]

1277

# rectangle around object

In [30]:
img=cv2.imread(r"D:\Downloads\4709944 vergil low res.jpg")
mc=max(c,key=cv2.contourArea)
x,y,w,h=cv2.boundingRect(mc)
cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),1)
cv2.imshow("contour",img)
cv2.waitKey()
cv2.destroyAllWindows()

# trial vergil

In [107]:
img=cv2.imread(r"D:\Downloads\4709944 vergil low res.jpg")
cv2.namedWindow("f1")
cv2.createTrackbar("low","f1",0,255,lambda x:None)
cv2.createTrackbar("high","f1",0,255,lambda x:None)
while True:
    gs=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    bi=cv2.GaussianBlur(gs,None,1)
    l=cv2.getTrackbarPos("low","f1")
    h=cv2.getTrackbarPos("high","f1")

    canny=cv2.Canny(bi,l,h)
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))
    #canny = cv2.morphologyEx(canny, cv2.MORPH_OPEN, kernel, iterations=1)
    canny = cv2.dilate(canny, kernel, iterations=1)
    
    c,h=cv2.findContours(canny,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)
    sc=sorted(c,key=cv2.contourArea,reverse=True)
    for i in sc:
        if cv2.contourArea(i)<700:
            continue
        x,y,w,h=cv2.boundingRect(i)
        img=cv2.imread(r"D:\Downloads\4709944 vergil low res.jpg")
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),1)
    cv2.imshow("f1",img)
    if cv2.waitKey(1) ==ord("q"):
        break
cv2.destroyAllWindows()
    

In [123]:
import cv2

# Load image once
original = cv2.imread(r"D:\Downloads\mixkit-people-in-the-subway-hall-in-tokyo-4454-hd-ready - frame at 0m2s.jpg")

cv2.namedWindow("f1")
cv2.createTrackbar("low", "f1", 50, 255, lambda x: None)
cv2.createTrackbar("high", "f1", 150, 255, lambda x: None)

while True:
    img = original.copy()
    gs = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    bi = cv2.GaussianBlur(gs, (5, 5), 1)

    l = cv2.getTrackbarPos("low", "f1")
    h = cv2.getTrackbarPos("high", "f1")

    canny = cv2.Canny(bi, l, h)

    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))
    canny = cv2.morphologyEx(canny, cv2.MORPH_CLOSE, kernel, iterations=1)
    canny = cv2.dilate(canny, kernel, iterations=1)

    c, _ = cv2.findContours(canny, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    sc = sorted(c, key=cv2.contourArea, reverse=True)

    combined = None
    for i in sc:
        if cv2.contourArea(i) < 500:
            continue
        if combined is None:
            combined = cv2.boundingRect(i)
        else:
            x, y, w, h = cv2.boundingRect(i)
            x0 = min(combined[0], x)
            y0 = min(combined[1], y)
            x1 = max(combined[0] + combined[2], x + w)
            y1 = max(combined[1] + combined[3], y + h)
            combined = (x0, y0, x1 - x0, y1 - y0)
    
    if combined:
        x, y, w, h = combined
        cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 0), 2)


    cv2.imshow("f1", img)
    if cv2.waitKey(1) == ord("q"):
        break

cv2.destroyAllWindows()


In [55]:
img=cv2.imread(r"D:\shapes_and_colors.jpg")
img1=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img1=cv2.GaussianBlur(img1,(7,7),1)
k=np.ones((5,5),dtype=np.uint8)
img2=cv2.morphologyEx(img1,op=cv2.MORPH_CLOSE,kernel=k,iterations=1)
can=cv2.Canny(img2,120,255)
c,h=cv2.findContours(can,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
mc=max(c,key=cv2.contourArea)
q=cv2.minAreaRect(mc)
fc=cv2.boxPoints(q)
fc=fc.astype(int)
cv2.drawContours(img,[fc],-1,(0.255,0),2)
cv2.imshow("contour",img)
cv2.waitKey()
cv2.destroyAllWindows()

[[276 408]
 [342 371]
 [412 495]
 [347 532]]


# getting centers 

In [42]:
img=cv2.imread(r"D:\shapes_and_colors.jpg")
img1=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img1=cv2.GaussianBlur(img1,(7,7),1)
k=np.ones((5,5),dtype=np.uint8)
img2=cv2.morphologyEx(img1,op=cv2.MORPH_CLOSE,kernel=k,iterations=1)
can=cv2.Canny(img2,120,255)
c,h=cv2.findContours(can,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
sc=sorted(c,key=cv2.contourArea,reverse=True)
for i in sc:
    mm=cv2.moments(i)
    x,y=(int(mm["m10"]/mm["m00"]),int(mm["m01"]/mm["m00"]))
    cv2.circle(img,(x,y),5,(255,255,0),-1)
cv2.imshow("contour",img)
cv2.waitKey()
cv2.destroyAllWindows()

# video edge detection

In [32]:
import cv2
import numpy as np 

# with trACK bar

In [13]:

vid=cv2.VideoCapture(r"D:\Downloads\18285863-uhd_1440_1920_29fps.mp4")
s,f1=vid.read()
s,f2=vid.read()
k=np.ones((5,5),dtype=np.uint8)
cv2.namedWindow("f1")
cv2.createTrackbar("low","f1",0,255,lambda x:None)
cv2.createTrackbar("high","f1",0,255,lambda x:None)
while True:
    f1=cv2.resize(f1,(1080,720))
    f2=cv2.resize(f2,(1080,720))
    
    frame=cv2.absdiff(f1,f2)
    gs=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    bi=cv2.GaussianBlur(gs,None,1)
    l=cv2.getTrackbarPos("low","f1")
    h=cv2.getTrackbarPos("high","f1")
    img2=cv2.morphologyEx(bi,op=cv2.MORPH_CLOSE,kernel=k,iterations=7)
    canny=cv2.Canny(img2,l,h)
    c,h=cv2.findContours(canny,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
    cv2.drawContours(f1,c,-1,(255,0,0),1)
    cv2.imshow("f1",f1)
    f1=f2
    s,f2=vid.read()
    if s == False:
        break
    if cv2.waitKey(100) == ord("q"):
        break
cv2.destroyAllWindows()

# without trackbar

In [50]:

vid=cv2.VideoCapture(r"D:\Downloads\mixkit-people-in-the-subway-hall-in-tokyo-4454-hd-ready.mp4")
s,f1=vid.read()
s,f2=vid.read()
while True:
    frame=cv2.absdiff(f1,f2)
    gs=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    bi=cv2.GaussianBlur(gs,None,3)
    canny=cv2.Canny(bi,30,60)
    c,h=cv2.findContours(canny,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)
    sc=sorted(c,key=cv2.contourArea,reverse=True)
    for i in sc:
        if cv2.contourArea(i)<500:
            continue
        q=cv2.minAreaRect(i)
        fc=cv2.boxPoints(q)
        fc=fc.astype(int)
        cv2.drawContours(f1,[fc],-1,(0,255,0),2)
    cv2.imshow("f1",f1)
    f1=f2
    s,f2=vid.read()
    if s == False:
        break
    if cv2.waitKey(50) == ord("q"):
        break
cv2.destroyAllWindows()

# some what working ver

In [19]:

vid=cv2.VideoCapture(r"D:\Downloads\mixkit-paris-pedestrian-path-4349-full-hd.mp4")
s,f1=vid.read()
s,f2=vid.read()
while True:
    f1=cv2.resize(f1,(1080,720))
    f2=cv2.resize(f2,(1080,720))
    frame=cv2.absdiff(f1,f2)
    gs=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    bi = cv2.GaussianBlur(gs,None,1)
    canny=cv2.Canny(bi,0,95)
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))
    #canny = cv2.morphologyEx(canny, cv2.MORPH_OPEN, kernel, iterations=1)
    canny = cv2.dilate(canny, kernel, iterations=1)

    c,h=cv2.findContours(canny,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)
    sc=sorted(c,key=cv2.contourArea,reverse=True)
    for i in sc:
        if cv2.contourArea(i)<700:
            continue
        x,y,w,h=cv2.boundingRect(i)
        cv2.rectangle(f1,(x,y),(x+w,y+h),(0,255,0),1)
    cv2.imshow("f1",f1)
    f1=f2
    s,f2=vid.read()
    if s == False:
        break
    if cv2.waitKey(40) == ord("q"):
        break
cv2.destroyAllWindows()

In [127]:
print(kernel)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# gpt pro code

In [88]:
import cv2

vid=cv2.VideoCapture(r"D:\Downloads\mixkit-people-in-the-subway-hall-in-tokyo-4454-hd-ready.mp4")
hog = cv2.HOGDescriptor()
hog.setSVMDetector(cv2.HOGDescriptor_getDefaultPeopleDetector())

while True:
    ret, frame = vid.read()
    if not ret:
        break

    frame = cv2.resize(frame, (640, 360))  # Resize for faster processing
    boxes, weights = hog.detectMultiScale(frame, winStride=(8, 8))

    for (x, y, w, h) in boxes:
        cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)

    cv2.imshow("People Detection", frame)

    if cv2.waitKey(30) == ord("q"):
        break

vid.release()
cv2.destroyAllWindows()


# approxPolydp

In [2]:
import cv2
import numpy as np

img = cv2.imread(r"D:\shapes_and_colors.jpg")
img1 = img.copy()

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
blur = cv2.GaussianBlur(gray, (5, 5), 1)
canny = cv2.Canny(blur, 100, 170)

contours, _ = cv2.findContours(canny, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

for c in contours:
    approx = cv2.approxPolyDP(c, 0.03 * cv2.arcLength(c, True), True)
    cv2.drawContours(img, [approx], -1, (0, 255, 0), 1)

    # Centroid for text position
    M = cv2.moments(c)
    if M["m00"] != 0:
        cx = int(M["m10"] / M["m00"])
        cy = int(M["m01"] / M["m00"])
    else:
        cx, cy = approx.ravel()[0], approx.ravel()[1]

    # Shape classification
    shape = "unknown"
    sides = len(approx)
    if sides == 3:
        shape = "triangle"
    elif sides == 4:
        x, y, w, h = cv2.boundingRect(approx)
        aspect_ratio = w / float(h)
        shape = "square" if 0.95 < aspect_ratio < 1.05 else "rectangle"
    elif sides == 5:
        shape = "pentagon"
    elif sides == 6:
        shape = "hexagon"
    elif sides > 6:
        shape = "circle"

    # Optional: Color detection at center
    b, g, r = img[cy, cx]
    color = "unknown"
    if r > 150 and g < 100 and b < 100:
        color = "red"
    elif g > 150 and r < 100 and b < 100:
        color = "green"
    elif b > 150 and r < 100 and g < 100:
        color = "blue"

    label = f"{color} {shape}"
    cv2.putText(img, label, (cx, cy), cv2.FONT_HERSHEY_COMPLEX, 0.5, (255, 0, 255), 1)

cv2.imshow("Original", img1)
cv2.imshow("Detected", img)
cv2.waitKey(0)
cv2.destroyAllWindows()